routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MainController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';

Route::get('/', [MainController::class, 'index'])->name('dashboard');

Route::prefix('master')->name('master.')->group(function () {
    Route::get('user', [UserController::class, 'index'])->name('users');
    Route::get('user/create', [UserController::class, 'create'])->name('users.create');
    Route::post('user/store', [UserController::class, 'store'])->name('users.store');
    Route::get('user/edit/{id}', [UserController::class, 'edit'])->name('users.edit');
    Route::post('user/update/{id}', [UserController::class, 'update'])->name('users.update');
    Route::delete('user/{id}', [UserController::class, 'destroy'])->name('users.delete');
});

// Route::resource('master/user', [UserController::class]);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MainController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;

class UserController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['users'] = User::get();

        return view('panel.users.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('panel.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'password' => 'required|confirmed',
            'email' => 'required|unique:users|email',
            'role' => 'required'
        ]);

        $newUser = $request->all();
        $newUser['password'] = bcrypt($newUser['password']);

        $log = User::create($newUser);

        $message = "New user has been created.";

        return redirect()->route('master.users')->with('success', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $editUser = User::findOrFail($id);
        $data['user'] = $editUser;

        return view('panel.users.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::findOrFail($id)->delete();
        $message = "User #" . $id . " has been deleted.";

        return redirect()->back()->with('success', $message);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
@extends('layouts.panel')

@section('content')
<div class="row">
	<div class="col-md-12 grid-margin">
		<div class="d-flex justify-content-between flex-wrap">
			<div class="d-flex align-items-end flex-wrap">
				<div class="mr-md-3 mr-xl-5">
					<h2>Dashboard</h2>
					<div class="d-flex">
						<i class="mdi mdi-home text-muted hover-cursor"></i>
						<p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Dashboard</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-12 stretch-card">
		<div class="card">
			<div class="card-body">
				<p class="card-title">Recent Purchases</p>
				<div class="table-responsive">
					<table id="recent-purchases-listing" class="table">
						<thead>
							<tr>
								<th>Name</th>
								<th>Status report</th>
								<th>Office</th>
								<th>Price</th>
								<th>Date</th>
								<th>Gross amount</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Jeremy Ortega</td>
								<td>Levelled up</td>
								<td>Catalinaborough</td>
								<td>$790</td>
								<td>06 Jan 2018</td>
								<td>$2274253</td>
							</tr>
							<tr>
								<td>Alvin Fisher</td>
								<td>Ui design completed</td>
								<td>East Mayra</td>
								<td>$23230</td>
								<td>18 Jul 2018</td>
								<td>$83127</td>
							</tr>
							<tr>
								<td>Emily Cunningham</td>
								<td>support</td>
								<td>Makennaton</td>
								<td>$939</td>
								<td>16 Jul 2018</td>
								<td>$29177</td>
							</tr>
							<tr>
								<td>Minnie Farmer</td>
								<td>support</td>
								<td>Agustinaborough</td>
								<td>$30</td>
								<td>30 Apr 2018</td>
								<td>$44617</td>
							</tr>
							<tr>
								<td>Betty Hunt</td>
								<td>Ui design not completed</td>
								<td>Lake Sandrafort</td>
								<td>$571</td>
								<td>25 Jun 2018</td>
								<td>$78952</td>
							</tr>
							<tr>
								<td>Myrtie Lambert</td>
								<td>Ui design completed</td>
								<td>Cassinbury</td>
								<td>$36</td>
								<td>05 Nov 2018</td>
								<td>$36422</td>
							</tr>
							<tr>
								<td>Jacob Kennedy</td>
								<td>New project</td>
								<td>Cletaborough</td>
								<td>$314</td>
								<td>12 Jul 2018</td>
								<td>$34167</td>
							</tr>
							<tr>
								<td>Ernest Wade</td>
								<td>Levelled up</td>
								<td>West Fidelmouth</td>
								<td>$484</td>
								<td>08 Sep 2018</td>
								<td>$50862</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/flash-message.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>    
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('error'))
    <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>    
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('warning'))
    <div class="alert alert-warning alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>    
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('info'))
    <div class="alert alert-info alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>    
        <strong>{{ $message }}</strong>
    </div>
@endif

  

@if ($errors->any())

<div class="alert alert-danger">

    <button type="button" class="close" data-dismiss="alert">×</button>    

    Please check the form below for errors

</div>

@endif

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>Majestic Admin</title>
		<link rel="stylesheet" href="{{asset('vendor/majestic')}}/vendors/mdi/css/materialdesignicons.min.css">
		<link rel="stylesheet" href="{{asset('vendor/majestic')}}/vendors/base/vendor.bundle.base.css">
		<link rel="stylesheet" href="{{asset('vendor/majestic')}}/css/style.css">
		<link rel="shortcut icon" href="{{asset('vendor/majestic')}}/images/favicon.png" />
	</head>
	<body>
		<div class="container-scroller">
			<div class="container-fluid page-body-wrapper full-page-wrapper">
				<div class="content-wrapper d-flex align-items-center auth px-0">
          			@yield('content')
				</div>
			</div>
		</div>

		<script src="{{asset('vendor/majestic')}}/vendors/base/vendor.bundle.base.js"></script>

		<script src="{{asset('vendor/majestic')}}/js/off-canvas.js"></script>
		<script src="{{asset('vendor/majestic')}}/js/hoverable-collapse.js"></script>
		<script src="{{asset('vendor/majestic')}}/js/template.js"></script>

	</body>
</html>

resources/views/layouts/panel.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        @include('layouts.partials.head')
    </head>
    <body>
        <div class="container-scroller">
            @include('layouts.partials.navbar')
            <div class="container-fluid page-body-wrapper">
                @include('layouts.partials.sidebar')
                <div class="main-panel">
                    <div class="content-wrapper">
                        @include('flash-message')
                        @yield('content')
                    </div>
                    @include('layouts.partials.footer')
                </div>
            </div>
        </div>
        @include('layouts.partials.script')
    </body>
</html>

resources/views/layouts/partials/footer.blade.php
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
       <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © {{date('Y')}} <a href="https://www.urbanui.com/" target="_blank">Urbanui</a>. All rights reserved.</span>
       <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
    </div>
</footer>

resources/views/layouts/partials/head.blade.php
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
@yield('meta')

<title>SI-PEA</title>

<!-- plugins:css -->
<link rel="stylesheet" href="{{asset('vendor/majestic')}}/vendors/mdi/css/materialdesignicons.min.css">
<link rel="stylesheet" href="{{asset('vendor/majestic')}}/vendors/base/vendor.bundle.base.css">
<!-- endinject -->
<!-- plugin css for this page -->
<link rel="stylesheet" href="{{asset('vendor/majestic')}}/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
<!-- End plugin css for this page -->
<!-- inject:css -->
<link rel="stylesheet" href="{{asset('vendor/majestic')}}/css/style.css">
<!-- endinject -->
<link rel="shortcut icon" href="{{asset('vendor/majestic')}}/images/favicon.png" />
@yield('link')
@yield('style')

resources/views/layouts/partials/navbar.blade.php
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
	<div class="navbar-brand-wrapper d-flex justify-content-center">
		<div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">  
			<a class="navbar-brand brand-logo" href="index.html"><img src="{{asset('vendor/majestic')}}/images/logo.svg" alt="logo"/></a>
			<a class="navbar-brand brand-logo-mini" href="index.html"><img src="{{asset('vendor/majestic')}}/images/logo-mini.svg" alt="logo"/></a>
			<button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
			    <span class="mdi mdi-sort-variant"></span>
			</button>
		</div>
	</div>
	<div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
		<ul class="navbar-nav navbar-nav-right">
			<li class="nav-item nav-profile dropdown">
				<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
				<img src="{{asset('vendor/majestic')}}/images/faces/face5.jpg" alt="profile"/>
				<span class="nav-profile-name">{{ Auth::user()->name }}</span>
				</a>
				<div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
					<a class="dropdown-item">
					    <i class="mdi mdi-settings text-primary"></i>
					    Settings
					</a>
                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <i class="mdi mdi-logout text-primary"></i>
                        Logout
					</a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
				</div>
			</li>
		</ul>
		<button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
		<span class="mdi mdi-menu"></span>
		</button>
	</div>
</nav>

resources/views/layouts/partials/script.blade.php
<!-- plugins:js -->
<script src="{{asset('vendor/majestic')}}/vendors/base/vendor.bundle.base.js"></script>
<!-- endinject -->
<!-- Plugin js for this page-->
<script src="{{asset('vendor/majestic')}}/vendors/chart.js/Chart.min.js"></script>
<script src="{{asset('vendor/majestic')}}/vendors/datatables.net/jquery.dataTables.js"></script>
<script src="{{asset('vendor/majestic')}}/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
<!-- End plugin js for this page-->
<!-- inject:js -->
<script src="{{asset('vendor/majestic')}}/js/off-canvas.js"></script>
<script src="{{asset('vendor/majestic')}}/js/hoverable-collapse.js"></script>
<script src="{{asset('vendor/majestic')}}/js/template.js"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<script src="{{asset('vendor/majestic')}}/js/dashboard.js"></script>
<script src="{{asset('vendor/majestic')}}/js/data-table.js"></script>
<script src="{{asset('vendor/majestic')}}/js/jquery.dataTables.js"></script>
<script src="{{asset('vendor/majestic')}}/js/dataTables.bootstrap4.js"></script>
<!-- End custom js for this page-->
@yield('script')

resources/views/layouts/partials/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
	<ul class="nav">
		<li class="nav-item">
			<a class="nav-link" href="{{route('dashboard')}}">
				<i class="mdi mdi-home menu-icon"></i>
				<span class="menu-title">Dashboard</span>
			</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" data-toggle="collapse" href="#master-data" aria-expanded="false" aria-controls="master-data">
				<i class="mdi mdi-circle-outline menu-icon"></i>
				<span class="menu-title">Master Data</span>
				<i class="menu-arrow"></i>
			</a>
			<div class="collapse" id="master-data">
				<ul class="nav flex-column sub-menu">
					<li class="nav-item">
						<a class="nav-link" href="{{route('master.users')}}">Users</a>
					</li>
				</ul>
			</div>
		</li>
	</ul>
</nav>

resources/views/panel/users/create.blade.php
@extends('layouts.panel')

@section('content')
<div class="row">
	<div class="col-md-12 grid-margin">
		<div class="d-flex justify-content-between flex-wrap">
			<div class="d-flex align-items-end flex-wrap">
				<div class="mr-md-3 mr-xl-5">
					<h2>Users</h2>
                    <div class="d-flex">
                        <i class="mdi mdi-home text-muted hover-cursor"></i>
                        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Master</p>
                        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Users</p>
                        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Create</p>
                    </div>
                    <div class="d-flex mt-2">
                        <a href="{{ route('master.users') }}" class="btn btn-primary">Back</a>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-12 grid-margin stretch-card">
		<div class="card">
			<div class="card-body">
				<p class="card-title">Create New User</p>
                @include('warning')
                <form action="{{ route('master.users.store') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" class="form-control" name="name" placeholder="Name" required>
                    </div>
                    <div class="form-group">
                        <label>Email address</label>
                        <input type="email" class="form-control" name="email" placeholder="Email" required>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" name="password" placeholder="Password" required>
                    </div>
                    <div class="form-group">
                        <label>Password Confirmation</label>
                        <input type="password" class="form-control" name="password_confirmation" placeholder="Password" required>
                    </div>
                    <div class="form-group">
                        <label>Role</label>
                        <select class="form-control" name="role" required>
                            <option value="admin">Admin</option>
                            <option value="member" selected>Member</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary" style="width: 100%;">Submit</button>
                </form>
            </div>
		</div>
	</div>
</div>
@endsection

resources/views/panel/users/edit.blade.php
@extends('layouts.panel')

@section('content')
<div class="row">
	<div class="col-md-12 grid-margin">
		<div class="d-flex justify-content-between flex-wrap">
			<div class="d-flex align-items-end flex-wrap">
				<div class="mr-md-3 mr-xl-5">
					<h2>Users</h2>
                    <div class="d-flex">
                        <i class="mdi mdi-home text-muted hover-cursor"></i>
                        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Master</p>
                        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Users</p>
                        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Edit</p>
                        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;{{$user->id}}</p>
                    </div>
                    <div class="d-flex mt-2">
                        <a href="{{ route('master.users') }}" class="btn btn-primary">Back</a>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-12 grid-margin stretch-card">
		<div class="card">
			<div class="card-body">
				<p class="card-title">Create New User</p>
                @include('warning')
                <form action="{{ route('master.users.update', $user->id) }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" class="form-control" name="name" placeholder="Name" required>
                    </div>
                    <div class="form-group">
                        <label>Email address</label>
                        <input type="email" class="form-control" name="email" placeholder="Email" required>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" name="password" placeholder="Password" required>
                    </div>
                    <div class="form-group">
                        <label>Password Confirmation</label>
                        <input type="password" class="form-control" name="password_confirmation" placeholder="Password" required>
                    </div>
                    <div class="form-group">
                        <label>Role</label>
                        <select class="form-control" name="role" required>
                            <option value="admin">Admin</option>
                            <option value="member" selected>Member</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary" style="width: 100%;">Submit</button>
                </form>
            </div>
		</div>
	</div>
</div>
@endsection

resources/views/panel/users/index.blade.php
@extends('layouts.panel')

@section('content')
<div class="row">
	<div class="col-md-12 grid-margin">
		<div class="d-flex justify-content-between flex-wrap">
			<div class="d-flex align-items-end flex-wrap">
				<div class="mr-md-3 mr-xl-5">
					<h2>Users</h2>
                    <div class="d-flex">
                        <i class="mdi mdi-home text-muted hover-cursor"></i>
                        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Master</p>
                        <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Users</p>
                    </div>
                    <div class="d-flex mt-2">
                        <a href="{{ route('master.users.create') }}" class="btn btn-primary">Create new User</a>
                    </div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-12 grid-margin stretch-card">
		<div class="card">
			<div class="card-body">
				<p class="card-title">Users</p>
				<div class="table-responsive">
					<table class="table table-bordered">
						<thead>
							<tr>
								<th width="10%">No</th>
								<th>Name</th>
								<th>Email</th>
								<th width="10%">Role</th>
								<th width="5%">Options</th>
							</tr>
						</thead>
						<tbody>
                            @foreach($users as $n => $user)
                            <tr>
                                <td>{{ $n+1 }}</td>
                                <td>{{ ucwords($user->name) }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ ucwords($user->role) }}</td>
                                <td>
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a type="button" class="btn btn-inverse-warning" href="{{route('master.users.edit', $user->id)}}">
                                            <i class="mdi mdi-pencil"></i>
                                        </a>
										<form method="POST" action="{{route('master.users.delete', $user->id)}}">
											@csrf
											@method('delete')
											<a type="submit" class="btn btn-inverse-danger delete-user" href="#">
												<i class="mdi mdi-delete"></i>
											</a>
										</form>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('script')
<script>
    $('.delete-user').click(function(e){
        e.preventDefault() // Don't post the form, unless confirmed
        if (confirm('Are you sure?')) {
            // Post the form
            $(e.target).closest('form').submit() // Post the surrounding form
        }
    });
</script>
@endsection

resources/views/warning.blade.php
@if($errors->any())
    <div class="alert alert-danger text-small text-danger pb-0">
        <ul>
        @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
        </ul>
    </div>
@endif